mysite/fantasybumps/urls.py
from django.conf.urls import url

from . import views

app_name = 'fantasybumps'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^crew/(?P<crew_id>[0-9]+)/$', views.crew_detail, name='crew_detail'),
    url(r'^rower/(?P<rower_id>[0-9]+)/$', views.rower_detail, name='rower_detail'),
    url(r'^profile/(?P<profile_id>[0-9]+)/$', views.profile_detail, name='profile_detail'),
    url(r'^table/$', views.table, name="table"),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^fantasybumps/', include('fantasybumps.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/fantasybumps/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Club(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Rower(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Crew(models.Model):
    boat = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    club = models.ForeignKey(Club)
    GENDER_CHOICES = (
        ('female', 'female'),
        ('male', 'male'),
    )
    gender = models.CharField(
        max_length=200,
        choices=GENDER_CHOICES
    )
    cox = models.ForeignKey(Rower, related_name="cox", null=True, default=None)
    stroke = models.ForeignKey(Rower, related_name="stroke", null=True, default=None)
    seven = models.ForeignKey(Rower, related_name="seven", null=True, default=None)
    six = models.ForeignKey(Rower, related_name="six", null=True, default=None)
    five = models.ForeignKey(Rower, related_name="five", null=True, default=None)
    four = models.ForeignKey(Rower, related_name="four", null=True, default=None)
    three = models.ForeignKey(Rower, related_name="three", null=True, default=None)
    two = models.ForeignKey(Rower, related_name="two", null=True, default=None)
    bow = models.ForeignKey(Rower, related_name="bow", null=True, default=None)
    result_1 = models.IntegerField(null=True)
    result_2 = models.IntegerField(null=True)
    result_3 = models.IntegerField(null=True)
    result_4 = models.IntegerField(null=True)

    def __str__(self):
        return str(self.club) + " " + self.boat


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cox = models.ForeignKey(Rower, related_name="profile_cox", null=True, default=None)
    stroke = models.ForeignKey(Rower, related_name="profile_stroke", null=True, default=None)
    seven = models.ForeignKey(Rower, related_name="profile_seven", null=True, default=None)
    six = models.ForeignKey(Rower, related_name="profile_six", null=True, default=None)
    five = models.ForeignKey(Rower, related_name="profile_five", null=True, default=None)
    four = models.ForeignKey(Rower, related_name="profile_four", null=True, default=None)
    three = models.ForeignKey(Rower, related_name="profile_three", null=True, default=None)
    two = models.ForeignKey(Rower, related_name="profile_two", null=True, default=None)
    bow = models.ForeignKey(Rower, related_name="profile_bow", null=True, default=None)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/fantasybumps/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import Q

from .models import Crew
from .models import Rower
from .models import Profile


def get_points(rower_id):
    crew = Crew.objects.get(Q(stroke_id=rower_id) | Q(seven_id=rower_id) | Q(six_id=rower_id) | Q(
        five_id=rower_id) | Q(four_id=rower_id) | Q(three_id=rower_id) | Q(two_id=rower_id) | Q(bow_id=rower_id))
    return crew.result_1 + crew.result_2 + crew.result_3 + crew.result_4


def index(request):
    crew_list = Crew.objects.order_by('club')
    context = {'crew_list': crew_list}
    return render(request, 'fantasybumps/index.html', context)


def crew_detail(request, crew_id):
    crew = get_object_or_404(Crew, pk=crew_id)
    return render(request, 'fantasybumps/crew_detail.html', {'crew': crew})


def rower_detail(request, rower_id):
    rower = Rower.objects.get(id=rower_id)
    crew_list = list(rower.cox.all()) + list(rower.stroke.all()) + list(rower.seven.all()) + list(rower.six.all()) + list(
        rower.five.all()) + list(rower.four.all()) + list(rower.three.all()) + list(rower.two.all()) + list(rower.bow.all())
    return render(request, 'fantasybumps/rower_detail.html', {'rower': rower, 'crew_list': crew_list})


def profile_detail(request, profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
        
    profile.points = 0

    crew = Crew.objects.get(cox_id=profile.cox.id)
    profile.points += crew.result_1 + crew.result_2 + crew.result_3 + crew.result_4

    profile.points += get_points(profile.stroke.id)
    profile.points += get_points(profile.seven.id)
    profile.points += get_points(profile.six.id)
    profile.points += get_points(profile.five.id)
    profile.points += get_points(profile.four.id)
    profile.points += get_points(profile.three.id)
    profile.points += get_points(profile.two.id)
    profile.points += get_points(profile.bow.id)

    return render(request, 'fantasybumps/profile_detail.html', {'profile': profile})


def table(request):
    profile_list = Profile.objects.order_by('user')

    for profile in profile_list:
        profile.points = 0

        crew = Crew.objects.get(cox_id=profile.cox.id)
        profile.points += crew.result_1 + crew.result_2 + crew.result_3 + crew.result_4

        profile.points += get_points(profile.stroke.id)
        profile.points += get_points(profile.seven.id)
        profile.points += get_points(profile.six.id)
        profile.points += get_points(profile.five.id)
        profile.points += get_points(profile.four.id)
        profile.points += get_points(profile.three.id)
        profile.points += get_points(profile.two.id)
        profile.points += get_points(profile.bow.id)

    context = {'profile_list': profile_list}
    return render(request, 'fantasybumps/table.html', context)

mysite/polls/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

mysite/fantasybumps/templates/fantasybumps/crew_detail.html
<h1>{{ crew.club.name }} - {{ crew.boat }} ({{ crew.name }})</h1>
<h2>Crew</h2>
<ul>
    <li>Cox: <a href="{% url 'fantasybumps:rower_detail' crew.cox.id %}">{{ crew.cox }}</a></li>
    <li>Stroke: <a href="{% url 'fantasybumps:rower_detail' crew.stroke.id %}">{{ crew.stroke}}</a></li>
    <li>7: <a href="{% url 'fantasybumps:rower_detail' crew.seven.id %}">{{ crew.seven }}</a></li>
    <li>6: <a href="{% url 'fantasybumps:rower_detail' crew.six.id %}">{{ crew.six }}</a></li>
    <li>5: <a href="{% url 'fantasybumps:rower_detail' crew.five.id %}">{{ crew.five }}</a></li>
    <li>4: <a href="{% url 'fantasybumps:rower_detail' crew.four.id %}">{{ crew.four }}</a></li>
    <li>3: <a href="{% url 'fantasybumps:rower_detail' crew.three.id %}">{{ crew.three }}</a></li>
    <li>2: <a href="{% url 'fantasybumps:rower_detail' crew.two.id %}">{{ crew.two }}</a></li>
    <li>Bow: <a href="{% url 'fantasybumps:rower_detail' crew.cox.id %}">{{ crew.bow }}</a></li>
</ul>
<h2>Results</h2>
<ul>
    <li>Tuesday: {{ crew.result_1 }}</li>
    <li>Wednesday: {{ crew.result_2 }}</li>
    <li>Thursday: {{ crew.result_3 }}</li>
    <li>Friday: {{ crew.result_4 }}</li>
</ul>

mysite/fantasybumps/templates/fantasybumps/index.html
<a href="{% url 'fantasybumps:table' %}">Leaderboard</a>

{% if crew_list %}
    <ul>
    {% for crew in crew_list %}
        <li><a href="{% url 'fantasybumps:crew_detail' crew.id %}">{{ crew.club }} - {{ crew.boat }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No crews are available.</p>
{% endif %}

mysite/fantasybumps/templates/fantasybumps/profile_detail.html
<h1>Profile: {{ profile.user.username }}</h1>
<h2>Crew</h2>
<ul>
    <li>Cox: <a href="{% url 'fantasybumps:rower_detail' profile.cox.id %}">{{ profile.cox }}</a></li>
    <li>Stroke: <a href="{% url 'fantasybumps:rower_detail' profile.stroke.id %}">{{ profile.stroke}}</a></li>
    <li>7: <a href="{% url 'fantasybumps:rower_detail' profile.seven.id %}">{{ profile.seven }}</a></li>
    <li>6: <a href="{% url 'fantasybumps:rower_detail' profile.six.id %}">{{ profile.six }}</a></li>
    <li>5: <a href="{% url 'fantasybumps:rower_detail' profile.five.id %}">{{ profile.five }}</a></li>
    <li>4: <a href="{% url 'fantasybumps:rower_detail' profile.four.id %}">{{ profile.four }}</a></li>
    <li>3: <a href="{% url 'fantasybumps:rower_detail' profile.three.id %}">{{ profile.three }}</a></li>
    <li>2: <a href="{% url 'fantasybumps:rower_detail' profile.two.id %}">{{ profile.two }}</a></li>
    <li>Bow: <a href="{% url 'fantasybumps:rower_detail' profile.cox.id %}">{{ profile.bow }}</a></li>
</ul>
Points: {{ profile.points }}

mysite/fantasybumps/templates/fantasybumps/rower_detail.html
<h1>{{ rower.name }}</h1>
{% if crew_list %}
    <ul>
    {% for crew in crew_list %}
        <li><a href="{% url 'fantasybumps:crew_detail' crew.id %}">{{ crew.club }} - {{ crew.boat }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No crews are available.</p>
{% endif %}

mysite/fantasybumps/templates/fantasybumps/table.html
{% if profile_list %}
    <table>
        <tr>
            <th>Player</th>
            <th>Points</th>
        </tr>
    {% for profile in profile_list %}
        <tr>
            <td><a href="{% url 'fantasybumps:profile_detail' profile.id %}">{{ profile.user.first_name }} {{ profile.user.last_name }}</a></td>
            <td>{{ profile.points }}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No players are available.</p>
{% endif %}